FORMAT: 1A
HOST: https://aglio.practice

# 測試 Aglio 用的 API 文件

## 內容
- 這裡可以對這份文件做一點說明，可能包含 API 相關的一些限制和規定
- 可以使用包含程式碼區塊的 Markdown 語法
```json
{
    "result": true,
    ...
}
```

# Group 文章
文章 API
<!-- include(post_api_doc.md) -->

# Group 使用者
使用者 API
<!-- include(user_api_doc.md) -->